---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/book":
    get:
      summary: List Books
      tags:
      - ListBooks
      parameters: []
      responses:
        '200':
          description: Successfully List Books
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
              required:
    post:
      summary: Add Book Record
      tags:
      - Books
      parameters: []
      responses:
        '201':
          description: Successfully Added Book Record
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
